### ISSUE TITLE
PiT 24.4: EndpointControllerConfiguration makes tests run with Spring boot based tests

### ISSUE THREAD

**Issue by manolo** [vaadin/hilla#2169]
### Describe the bug

When upgrading to version 24.4.0.alpha3 the demo project hosted in spring project fails when running tests

I have tried to add the maven plugin to the `build` block as described in this [issue](https://github.com/vaadin/platform/issues/5041), but still failing

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method csrfChecker in com.vaadin.hilla.EndpointControllerConfiguration required a bean of type 'jakarta.servlet.ServletContext' that could not be found.


Action:

Consider defining a bean of type 'jakarta.servlet.ServletContext' in your configuration.
```

### Expected-behavior

tests pass

### Reproduction

```
## clone project and change to the folder `complete`
git clone https://github.com/spring-guides/gs-crud-with-vaadin.git
cd gs-crud-with-vaadin/complete
## Increase version
perl -0777 -pi -e 's|(<vaadin.version>)([^\s]+)(</vaadin.version>)|${1}24.4.0.alpha8${3}|g' pom.xml

## Add prereleases repositories
perl -pi -e  \
  's|(\s*)(</properties>)|$1$2\n$1<repositories><repository><id>v</id><url>https://maven.vaadin.com/vaadin-prereleases</url></repository></repositories>|' \
  pom.xml

perl -pi -e \
  's|(\s*)(</properties>)|$1$2\n$1<pluginRepositories><pluginRepository><id>v</id><url>https://maven.vaadin.com/vaadin-prereleases</url></pluginRepository></pluginRepositories>|' \
  pom.xml

## Run tests
mvn clean test
```

### System Info

Vaadin 24.4.0.alpha3-alpha8

**Comment by Artur-** [comment]
This was fixed a long time ago I think

**Comment by manolo** [comment]
It is still a problem, if you run the same project in 24.4.0.alpha20 it still fail the test with this error:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method csrfChecker in com.vaadin.hilla.EndpointControllerConfiguration required a bean of type 'jakarta.servlet.ServletContext' that could not be found.
```

**Comment by Artur-** [comment]
Why do you have `webEnvironment = SpringBootTest.WebEnvironment.NONE`? Then you don't have a web environment and there is no servlet context

**Comment by taefi** [comment]
I believe `webEnvironment = SpringBootTest.WebEnvironment.MOCK` is clearly resolving this issue. 
@manolo I'm closing this issue, but feel free to reopen if there were any other concerns.
